# Generated by Django 5.1.6 on 2025-03-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0005_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
